theme: gem 'minimal-mistakes-jekyll', :git => 'https://github.com/mmistakes/minimal-mistakes.git', :branch => 'color-skins'
title: Asim Iqbal
logo: img/profile.jpg
description: AI Neuroscientist, UZH|ETH Zürich
